openapi: 3.0.0
info:
  title: Data Reading API
  version: 1.0.0
  description: API for reading health monitoring data from patients and devices.
servers:
  - url: https://example.com/api/v1
paths:
  /patients/{patientId}/measurements:
    get:
      summary: Fetch measurements for a specific patient
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of measurements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
components:
  schemas:
    Measurement:
      type: object
      properties:
        type:
          type: string
        value:
          type: object
        timestamp:
          type: string
          format: datetime
        deviceId:
          type: string
