openapi: 3.0.0
info:
  title: Reports API
  version: 1.0.0
  description: API for generating and retrieving health reports.
paths:
  /reports/{userId}:
    get:
      summary: Get health reports for a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of health reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
components:
  schemas:
    Report:
      type: object
      properties:
        reportId:
          type: string
        dateGenerated:
          type: string
          format: date-time
        contents:
          type: string
